volumes:
  kestra_data:
  kestra_postgres_data:
  kestra_workdir:

services:
  kestra_postgres:
    image: postgres:17-alpine
    container_name: kestra_postgres
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra -d kestra"]
      interval: 5s
      retries: 5
    networks:
      - kestra-net

  kestra:
    image: kestra/kestra:v1.1
    container_name: docker-kestra-only-kestra-1
    command: server standalone
    depends_on:
      kestra_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    # This pulls the variables created by your script
    env_file:
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          encryption:
            secret-key: "${KESTRA_ENCRYPTION_KEY}"
          server:
            basicAuth:
              username: "admin@kestra.io"
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            username: kestra
            password: k3str4
    networks:
      - kestra-net

networks:
  kestra-net:
    driver: bridge