services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - pg-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      # Optional: makes pgAdmin store sessions on disk rather than memory
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"  # changed from 8080 to avoid conflict
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-provisioning/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-provisioning/pgpass:/pgpass:ro
    depends_on:
      - db
    networks:
      - pg-network

volumes:
  vol-pgdata:
  vol-pgadmin_data:

networks:
  pg-network:
